version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "patient-checkout"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-146ic6a6vrgva"
s3_prefix = "patient-checkout"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
